package com.novacrm.chat;

import com.novacrm.estudiante.Estudiante;
import com.novacrm.shared.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/** Mensaje privado entre dos estudiantes del mismo proyecto. */
@Entity
@Table(name = "chat_directo_mensaje", indexes = {
        @Index(name = "idx_chat_directo_remitente", columnList = "remitente_id, created_at"),
        @Index(name = "idx_chat_directo_destinatario", columnList = "destinatario_id, created_at")
})
public class ChatDirectoMensaje extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "remitente_id", nullable = false)
    private Estudiante remitente;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "destinatario_id", nullable = false)
    private Estudiante destinatario;

    /**
     * Orden de llegada, puesto por la base al insertar.
     *
     * <p>{@code createdAt} no basta para ordenar: lo pone el reloj del sistema
     * y dos mensajes escritos en el mismo milisegundo salen con el mismo valor,
     * con lo que la conversacion puede leerse al reves.
     *
     * <p>No lo escribe la aplicacion: si lo hiciera volveriamos a depender del
     * reloj, que es el problema.
     */
    // @Generated: la pone la base al insertar y hay que volver a leerla. Sin
    // esto, la entidad recien guardada se queda con la secuencia en nulo, y
    // cualquier comparacion contra ese nulo deja fuera la fila —se pierde un
    // mensaje al subir por la conversacion, sin error ninguno—.
    @org.hibernate.annotations.Generated(event = org.hibernate.generator.EventType.INSERT)
    @Column(name = "secuencia", insertable = false, updatable = false, columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private Long secuencia;

    public Long getSecuencia() { return secuencia; }

    @Column(nullable = false, columnDefinition = "TEXT")
    private String contenido;

    @Column(nullable = false)
    private boolean editado = false;

    @Column(name = "en_respuesta_a")
    private java.util.UUID enRespuestaA;

    @Column(nullable = false)
    private boolean reenviado = false;

    /**
     * Cuando lo abrio el destinatario; nulo mientras no lo haya visto.
     */
    @Column(name = "leido_at")
    private java.time.Instant leidoAt;

    /**
     * Los archivos que acompanan al mensaje.
     *
     * <p>Se cargan con el mensaje porque la pantalla los pinta en la misma
     * burbuja: pedirlos aparte serian tantas consultas como mensajes tenga la
     * conversacion.
     */
    @OneToMany(mappedBy = "mensaje", cascade = CascadeType.ALL, orphanRemoval = true)
    private java.util.List<ChatAdjunto> adjuntos = new java.util.ArrayList<>();

    public java.util.List<ChatAdjunto> getAdjuntos() { return adjuntos; }

    public java.time.Instant getLeidoAt() { return leidoAt; }
    public void setLeidoAt(java.time.Instant leidoAt) { this.leidoAt = leidoAt; }

    public boolean isEditado() { return editado; }
    public void setEditado(boolean editado) { this.editado = editado; }

    public java.util.UUID getEnRespuestaA() { return enRespuestaA; }
    public void setEnRespuestaA(java.util.UUID enRespuestaA) { this.enRespuestaA = enRespuestaA; }

    public boolean isReenviado() { return reenviado; }
    public void setReenviado(boolean reenviado) { this.reenviado = reenviado; }

    public Estudiante getRemitente() { return remitente; }
    public void setRemitente(Estudiante remitente) { this.remitente = remitente; }
    public Estudiante getDestinatario() { return destinatario; }
    public void setDestinatario(Estudiante destinatario) { this.destinatario = destinatario; }
    public String getContenido() { return contenido; }
    public void setContenido(String contenido) { this.contenido = contenido; }
}
