spring:
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  cors:
    allowed-origins: http://localhost:3000
